"""Add LabResult model

Revision ID: 520fe68c686d
Revises: acb91cd044a1
Create Date: 2025-06-06 22:21:59.284585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '520fe68c686d'
down_revision = 'acb91cd044a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=200), nullable=False),
    sa.Column('test_type', sa.String(length=100), nullable=True),
    sa.Column('test_date', sa.DateTime(), nullable=False),
    sa.Column('result_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reference_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_interactions', schema=None) as batch_op:
        batch_op.drop_column('interaction_metadata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interaction_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))

    op.drop_table('lab_results')
    # ### end Alembic commands ###
