"""Add currency column to payments table

Revision ID: acb91cd044a1
Revises: 
Create Date: 2025-06-06 12:28:29.104991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'acb91cd044a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('receipt_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('receipt_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('metadata')
        batch_op.drop_column('notes')
        batch_op.drop_column('receipt_sent_at')
        batch_op.drop_column('receipt_sent')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
